/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameVisual;

import Librerias.CircleLabels;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.*;

/**
 *
 * @author Raim
 */
public class GameCFour extends JFrame {    
    private final static byte CANT_ROW = 6;
    private final static byte CANT_COL = 7;
    private final static byte CONNECTED_WIN = 4;//VALOR PARA GANAR
    private final static int SIZE_PIEZA = 70;
    
    private JPanel tablero;
    private JLayeredPane jlp;    
    
    private final Color background = new Color(200, 200, 200);//por si quiero probar algun color
    
    //private JLabel[][] circulos; //potencial a usar
    private CircleLabels cl;
    JPanel [][] square;
    private JButton col1, col2, col3, col4, col5, col6, col7;//para agregar circulos a cada columna
    private char colorActual = 'R';
    //private Color c = new Color
    /**
     * Creates new form GameCFour
     */
    public GameCFour() {
        initComponents();
        createBoard();
    }    
    
    public void createBoard(){
        Dimension boardSize = new Dimension(600, 600);
        jlp = new JLayeredPane();
        getContentPane().add(jlp);
        jlp.setPreferredSize(boardSize);
        
        tablero = new JPanel();
                
        jlp.add(tablero, JLayeredPane.DEFAULT_LAYER);
        tablero.setLayout( new GridLayout(6, 7));
        tablero.setPreferredSize(boardSize);
        tablero.setBounds(0, 50, boardSize.width, boardSize.height);
        
        getContentPane().add(tablero);
        square = new JPanel[CANT_ROW][CANT_COL];
        //MOMENTO DE PRUEBA DE AGREGAR UN CIRCULO
        
        addButtons();
                
        for (int i = 0; i < CANT_ROW; i++) {
            for(int j = 0; j < CANT_COL; j++){
                square [i][j] = new JPanel( new BorderLayout() );
                CircleLabels cl = new CircleLabels();
                square[i][j].add(cl);
                cl.setColorIcon('D');
                tablero.add(square [i][j]);
                //int row = (i / CANT_ROW) % 2;
                //if (row == 0){//0, 2, 4                  
                square[i][j].setBackground(Color.white );    
                    //square[i][j].setBorder(new Border());
                //}else{                 
                //square[i][j].setBackground((i + j) % 2 == 0 ? Color.white : Color.black ); 
                //}
            }           
        }      
        
        
//        
//        try{            
//            CircleLabels cl = new CircleLabels();
//            tablero.add(cl);
//            cl.setColor('D');
//        }catch (Exception ex){
//            System.out.println(ex.getMessage());
//            ex.printStackTrace();
//        }
    }    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(661, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GameCFour().setVisible(true);
            }
        });
    }
    
    private boolean downCircle(int col){
        for (int i = CANT_ROW-1; i >= 0; i--) {
            CircleLabels este = (CircleLabels)square[i][col].getComponent(0);
            if (este.descripcion.equalsIgnoreCase("Ficha Blank")){
                este.setColorIcon(colorActual);
                System.out.println(este.color);
                return fourConnected(i, col, colorActual);
            }
        }
        return false;
    }
    
    private void col1ActionPerformed(ActionEvent evt) {
        //Aqui el codigo
        int col = 0;
        if (downCircle(col))
            System.out.println("Ganaste");
        colorActual = colorActual=='R'?'A':'R';
    }
    
    private void col2ActionPerformed(ActionEvent evt) {
        //Aqui el codigo
        int col = 1;
        if (downCircle(col))
            System.out.println("Ganaste");
        colorActual = colorActual=='R'?'A':'R';
    }
    
    private void col3ActionPerformed(ActionEvent evt) {
        //Aqui el codigo
        int col = 2;
        if (downCircle(col))
            System.out.println("Ganaste");
        colorActual = colorActual=='R'?'A':'R';
    }
    
    private void col4ActionPerformed(ActionEvent evt) {
        //Aqui el codigo
        int col = 3;
        if (downCircle(col))
            System.out.println("Ganaste");
        colorActual = colorActual=='R'?'A':'R';
    }
    
    private void col5ActionPerformed(ActionEvent evt) {
        //Aqui el codigo
        int col = 4;
        if (downCircle(col))
            System.out.println("Ganaste");
        colorActual = colorActual=='R'?'A':'R';
    }
    
    private void col6ActionPerformed(ActionEvent evt) {
        //Aqui el codigo
        int col = 5;
        if (downCircle(col))
            System.out.println("Ganaste");
    }
    
    private void col7ActionPerformed(ActionEvent evt) {
        //Aqui el codigo
        int col = 6;
        if (downCircle(col))
            System.out.println("Ganaste");
        colorActual = colorActual=='R'?'A':'R';
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private boolean fourConnected(int row, int col, char color){
        if (connectedLineH(row, color) || connectedLineV(col, color) || connectedLineDA(row, col, color) || connectedLineDD(row, col, color))
            return true;
        return false;
    }
    
    private boolean connectedLineH(int row, char color){
        CircleLabels h;
        int conectados = 0;
        for (int contador = 0; contador < 7; contador++) {
            h = (CircleLabels)square[row][contador].getComponent(0);
            if (h.color == color){
                conectados++;
                if (conectados>=4)
                    break;
            }else
                conectados=0;
        }
        System.out.println(conectados);
        if (conectados >= 4)
            return true;
        return false;
    }
    
    private boolean connectedLineV(int col, char color){
        CircleLabels h;
        int conectados = 0;
        for (int contador = 0; contador < 6; contador++) {
            h = (CircleLabels)square[contador][col].getComponent(0);
            if (h.color == color){
                conectados++;
                if (conectados>=4)
                    break;
            }else
                conectados = 0;
        }
        
        if (conectados >= 4)
            return true;
        return false;
    }
    
    private boolean connectedLineDD(int row, int col, char color){
        while(col>0 || row>0){
            col--;
            row--;
        }
        int contador = 0;
        CircleLabels h;
        
        while(col<=6 || row<=5){
            try{
                h = (CircleLabels)square[col][row].getComponent(0);
            }catch(Exception e){
                break;
            }
            if (h.color == color){
                contador++;
                if (contador>=4)
                    break;
            }else
                contador = 0;
            col++; 
            row++;
        }
        if (contador>=4)
            return true;
        return false;
    }
    
    private boolean connectedLineDA(int row, int col, char color){
        while(col>0 || row<5){
            col--;
            row++;
        }
        int contador = 0;
        CircleLabels h;
        
        while(col<=6 || row>=0){
            try{
                h= (CircleLabels)square[col][row].getComponent(0);
            }catch(Exception e){
                break;
            }
            if (h.color == color){
                contador++;
                if (contador>=4)
                    break;
            }else
                contador = 0;
            col++; 
            row--;
        }
        
        if (contador>=4)
            return true;
        return false;
    }
    
    private void addButtons() {
        String texto = "Conectar";
        Dimension dbotones = new Dimension(80, 30);
        
        col1 = new JButton();
        col1.setText(texto);
        col1.setSize(dbotones);
        getContentPane().add(col1);
        col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col1ActionPerformed(evt);
            }
        });
        
        col2 = new JButton();
        col2.setText(texto);
        col2.setSize(dbotones);
        getContentPane().add(col2);
        col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col2ActionPerformed(evt);
            }
        });
        
        col3 = new JButton();
        col3.setText(texto);
        col3.setSize(dbotones);
        getContentPane().add(col3);
        col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col3ActionPerformed(evt);
            }
        });
        
        col4 = new JButton();
        col4.setText(texto);
        col4.setSize(dbotones);
        getContentPane().add(col4);
        col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col4ActionPerformed(evt);
            }
        });
        
        col5 = new JButton();
        col5.setText(texto);
        col5.setSize(dbotones);
        getContentPane().add(col5);
        col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col5ActionPerformed(evt);
            }
        });
        
        col6 = new JButton();
        col6.setText(texto);
        col6.setSize(dbotones);
        getContentPane().add(col6);
        col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col6ActionPerformed(evt);
            }
        });
        
        col7 = new JButton();
        col7.setText(texto);
        col7.setSize(dbotones);
        getContentPane().add(col7);
        col7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col7ActionPerformed(evt);
            }
        });
        
        col1.setLocation(0, 10);
        col2.setLocation(85, 10);
        col3.setLocation(170, 10);
        col4.setLocation(255, 10);
        col5.setLocation(340, 10);
        col6.setLocation(425, 10);
        col7.setLocation(510, 10);
    }
}
