/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameVisual;

import Librerias.CircleLabels;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.*;

/**
 *
 * @author Raim
 */
public class GameCFour extends JFrame {    
    private final static byte CANT_ROW = 6;
    private final static byte CANT_COL = 7;
    private final static byte CONNECTED_WIN = 4;//VALOR PARA GANAR
    private JPanel tablero;
    private JLayeredPane jlp;    
    private final Color background = new Color(200, 200, 200);//por si quiero probar algun color
    private JLabel[][] circulos; //potencial a usar
    private final static int SIZE_PIEZA = 70;
    
    //private Color c = new Color
    /**
     * Creates new form GameCFour
     */
    public GameCFour() {
        initComponents();
        createBoard();
    }
    
    public void createBoard(){
        Dimension boardSize = new Dimension(600, 600);
        jlp = new JLayeredPane();
        getContentPane().add(jlp);
        jlp.setPreferredSize(boardSize);
        
        tablero = new JPanel();
        jlp.add(tablero, JLayeredPane.DEFAULT_LAYER);
        tablero.setLayout( new GridLayout(6, 7));
        tablero.setPreferredSize(boardSize);
        tablero.setBounds(0, 0, boardSize.width, boardSize.height);
        
        getContentPane().add(tablero);
        JPanel [][] square = new JPanel[CANT_ROW][CANT_COL];
        //MOMENTO DE PRUEBA DE AGREGAR UN CIRCULO
        try{            
            tablero.add(new CircleLabels());
        }catch (Exception ex){
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
        
        for (int i = 0; i < CANT_ROW; i++) {
            for(int j = 0; j < CANT_COL; j++){
                square [i][j] = new JPanel( new BorderLayout() );
                tablero.add(square [i][j]);
                int row = (i / CANT_ROW) % 2;
                if (row == 0)//0, 2, 4
                    square[i][j].setBackground((i + j) % 2 == 0 ? Color.black : Color.white );
                else
                    square[i][j].setBackground((i + j) % 2 == 0 ? Color.white : Color.black ); 
            }           
        }
             
    }    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameCFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GameCFour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
