/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GameVisual;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import Librerias.Usuarios;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raim
 */
public class Ranking extends javax.swing.JInternalFrame {
    private RandomAccessFile rUsuarios;
    private ArrayList<Usuarios> listUsuarios;
    
    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();
        try{
            rUsuarios = new RandomAccessFile("GameFiles" + File.separator 
                    + "usuarios.cfo", "r");
            listUsuarios = new ArrayList<>();  
            //Agregar usuarios a la lista y luego ordenarlos
            addUsersToList();
            sortListUsuarios();
        }catch(IOException io){
            System.out.println(io.getMessage());
        }
    }
    
    private void addUsersToList() throws IOException{
        listUsuarios.clear();
        rUsuarios.seek(0);
        while(rUsuarios.getFilePointer() < rUsuarios.length()){
            String username = rUsuarios.readUTF();
            rUsuarios.readUTF();
            String nombre = rUsuarios.readUTF();
            rUsuarios.readLong();
            rUsuarios.skipBytes(8);
            int puntos = rUsuarios.readInt();
            //Agregar solo los datos necesarios para el ranking
            listUsuarios.add(new Usuarios(0, 0, puntos, nombre, username, "", 0));            
        }    
               
    }
    
    private void sortListUsuarios(){
        ArrayList<Usuarios> tmpUsers = new ArrayList<>();
        Usuarios userPlaceholder;
        if (listUsuarios.isEmpty())
            return;
        
        int row = 0;
        while (listUsuarios.size() > 0){                 
            userPlaceholder = listUsuarios.get(0);
            for (int i = listUsuarios.size() - 1; i > 0; i--){      
                Usuarios comparisonUser = listUsuarios.get(i);
                userPlaceholder = userPlaceholder.getPuntos() > comparisonUser.getPuntos() ?
                        userPlaceholder : comparisonUser;
                
                System.out.printf("P1: %d - P2: %d %n", userPlaceholder.getPuntos(), 
                        comparisonUser.getPuntos());
            }
            Object[] insertado = {row + 1, userPlaceholder.getNombre(), 
                userPlaceholder.getUsername(), userPlaceholder.getPuntos()};
            //( (DefaultTableModel) table.getModel() ).insertRow(dest+1, getValuesForNewRow());
            ( (DefaultTableModel) jTRanks.getModel() ).insertRow(row++, insertado);
            
            listUsuarios.remove(userPlaceholder);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTRanks = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();

        jTRanks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Usuario", "Puntos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTRanks);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTRanks;
    // End of variables declaration//GEN-END:variables
}
